### ISSUE TITLE
Output location and output format

### ISSUE THREAD

**Issue by zcsheng95** [dellytools/sansa#2]
Hi,
Is it feasible to use delly sansa to specify the output location and format?
I was getting the output bcf file at the current directory and ideally, I would like to get a tab-delimited table to examine fusion candidates like the one in the README.md.
The command I used is below: 
$sansa annotate -i Name -g ./genome/Homo_sapiens.GRCh38.102.chr.gff3.gz ./tags/${stem}.vcf

Thanks,
Jeff

**Comment by tobiasrausch** [comment]
`sansa annotate` lists the available options. `-o` specifies the output location. For instance:

`sansa annotate -i Name -g ./genome/Homo_sapiens.GRCh38.102.chr.gff3.gz -o /tmp/out.tsv.gz delly.bcf`

`zcat /tmp/out.tsv.gz | head`

**Comment by zcsheng95** [comment]
Thanks a lot, I was not aware it is a gzipped file.
