### ISSUE TITLE
About the SV Result 

### ISSUE THREAD

**Issue by ClarenceHsiang** [dellytools/sansa#4]
![image](https://user-images.githubusercontent.com/57841470/182500985-a848685f-68ba-4c7b-a6e2-1542319b03d1.png)
![image](https://user-images.githubusercontent.com/57841470/182501024-18ec70f4-a4de-45a0-8e6c-6c69a7d89db2.png)

Dear Sansa team:

Good morning,

When I ran the sansa for annotation, here showed a message as below:
-------------
[W::vcf_parse_info] INFO/END=3751954 is smaller than POS at Pmu2_1:19179541
---------------
And the some deletion showed very weird result, the deletion sequence is almost 50% chromosome.

Is there any connection in the warning message and the result??

Thank you very much.

Best

Clarence

**Comment by tobiasrausch** [comment]
Looks like some of your SVs have an end coordinate smaller than the start? That should not happen. What version of delly did you use: `delly --version`

**Comment by ClarenceHsiang** [comment]
Delly version: v0.8.1
 using Boost: v1.67.0
 using HTSlib: v1.9

**Comment by tobiasrausch** [comment]
Thanks. Delly previously used INFO/END also for interchromosomal translocations. This has been deprecated because of the above error. Interchromosomal translocations (BND SV type) now use INFO/CHR2 and INFO/POS2. You need to update delly (>=v1.0.3) and then it should be fine.
